# Generated by Django 3.0.1 on 2019-12-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('numero_inscricao', models.BigIntegerField()),
                ('data_criacao', models.DateField(null=True)),
                ('incricao_estadual', models.CharField(default='', max_length=200, null=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
    ]
